spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/dilfly_test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  jackson:
    time-zone: UTC

  flyway:
    schemas: public